[site]
title = "Homepage"
description = "Researcher at the University of Example."
favicon = "/favicon.svg"
last_updated = "March 11, 2026"

[author]
name = "Xinyi Wang"
title = "Researcher"
institution = "NUAA"
email = "xinyi.wang@nuaa.edu.cn"
avatar = "/xinyiwang.jpg"

[social]
# Contact information (leave blank or delete to hide)

location = "Nanjing, China"
location_url = "https://maps.google.com"
location_details = [
  "Room 900, the Main Building,",
  "Nanjing University of Aeronautics and Astronautics, Nanjing, China"
]
google_scholar = "https://scholar.google.com/citations?user=1BZm6i8AAAAJ&hl=en"
orcid = "https://orcid.org/my-orcid?orcid=0009-0005-2254-6375"
github = "https://github.com"
# linkedin = "https://linkedin.com"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Blog"
type = "page"
target = "blog"
href = "/blog"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
